# -*- coding: utf-8 -*-
{
    'name': "SuperMarket Pro",
    'summary': """
        Professional SuperMarket Management System for Odoo-15""",
    'description': """
        Complete SuperMarket Management Solution for Odoo-15
        Features: Sales, Purchases, Inventory, Customer Management, Financial Tracking, and Advanced Reporting
    """,
    'author': "abdallaalsafy",
    'website': "http://www.facebook.com/abdalla6alsafy",
    'category': 'Sales',
    'version': '15,0,0,0',
    'depends': ['base'],
    'data': [
        'security/access_groups.xml',
        'security/ir.model.access.csv',

        'data/sequences.xml',
        'data/default_units.xml',

        'wizards/merg_buys.xml',
        'wizards/merg_buys_r.xml',
        # 'wizards/merg_sells.xml',
        # 'wizards/merg_sells_r.xml',
        'wizards/update_goods.xml',
        'wizards/willing.xml',
        'wizards/about.xml',
        'wizards/search_buys_goods.xml',

        'views/customers.xml',
        'views/vendors.xml',
        'views/stores.xml',
        'views/categorys.xml',
        'views/goods.xml',
        'views/units.xml',
        'views/catg_units.xml',
        'views/buys.xml',
        'views/buys_r.xml',
        'views/sells.xml',
        'views/sells_r.xml',
        'views/buys_goods.xml',
        'views/buys_r_goods.xml',
        'views/sells_goods.xml',
        'views/sells_r_goods.xml',
        'views/charges.xml',
        'views/charges_goods.xml',
        'views/spending.xml',
        'views/customers_in.xml',
        'views/customers_out.xml',
        'views/vendors_in.xml',
        'views/vendors_out.xml',
        'views/inventorys.xml',
        'views/inventorys_goods.xml',

        'querys/goods_calc.xml',
        'querys/goods_stores.xml',
        'querys/alarms.xml',

        'views/menus.xml',

        'reports/reports_rtl/alarms_report.xml',
        'reports/reports_rtl/buys_goods_report.xml',
        'reports/reports_rtl/buys_r_goods_report.xml',
        'reports/reports_rtl/buys_r_report.xml',
        'reports/reports_rtl/buys_report.xml',
        'reports/reports_rtl/charges_goods_report.xml',
        'reports/reports_rtl/charges_report.xml',
        'reports/reports_rtl/customers_deuoon_report.xml',
        'reports/reports_rtl/customers_in_report.xml',
        'reports/reports_rtl/customers_out_report.xml',
        'reports/reports_rtl/customers_report.xml',
        'reports/reports_rtl/goods_calc_report.xml',
        'reports/reports_rtl/goods_report.xml',
        'reports/reports_rtl/goods_stores_report.xml',
        'reports/reports_rtl/inventorys_report.xml',
        'reports/reports_rtl/sells_goods_report.xml',
        'reports/reports_rtl/sells_r_goods_report.xml',
        'reports/reports_rtl/sells_r_report.xml',
        'reports/reports_rtl/sells_report.xml',
        'reports/reports_rtl/spending_report.xml',
        'reports/reports_rtl/vendors_deuoon_report.xml',
        'reports/reports_rtl/vendors_in_report.xml',
        'reports/reports_rtl/vendors_out_report.xml',
        'reports/reports_rtl/vendors_report.xml',
        'reports/paper_format.xml',
        'reports/reports_actions.xml',

    ],
    'demo': [
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
